### PR TITLE
Adding LICENSE_FILES

### PR DESCRIPTION
**Pull request by mwestphal**

### CODE REVIEW

**Comment by mwestphal** [comment]
@dgobbi : I'm not sure this is correct is this is valid when vtk-dicom is built as a remote modules but not valid when building against vtk 9.1.

**Comment by dgobbi** [comment]
The file vtk.module is only for the remote module.  For external builds, the module file is [Source/dicom.module](../blob/master/Source/dicom.module).

Can you link to the corresponding change in VTK?  I'm curious about how `LICENSE_FILES` will be used by the VTK module system.

**Comment by mwestphal** [comment]
Sure here it is: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8889

In short, VTK module can now have their license installed in install/share/licenses/moduleName/

**Comment by dgobbi** [comment]
Thanks. Makes sense.

**Pull request merged**
