### PR TITLE
C++11 compiler related warning fixes

### PR DESCRIPTION
**Pull request by sankhesh**
Added VTK_OVERRIDE and VTK_DELETE_FUNCTION macros

### CODE REVIEW

**Comment by dgobbi** [comment]
This is tricky because vtk-dicom needs to maintain compatibility with older versions of VTK.  I'll get something merged for this over the next few days.

**Comment by sankhesh** [comment]
Maybe define the VTK_OVERRIDE and VTK_DELETE_FUNCTION macros within vtk-dicom if using older VTK?

**Comment by dgobbi** [comment]
I already tried that a few months ago.  The older versions of the VTK wrappers can't handle it.  If they see "void PrintSelf() VTK\_OVERRIDE;" the VTK 6 wrappers fail, even if VTK\_OVERRIDE has an empty definition.

I've made a branch that adds a bunch of ugly ifdef's, I think it's the only way:
https://github.com/dgobbi/vtk-dicom/tree/warn-c%2B%2B11

**Comment by dgobbi** [comment]
I've merged a messy fix (9a4c5c3c) that also builds against VTK 5 and VTK 6.

**Pull request closed without merging**
